### PR TITLE
Fix module name for Show -> Update in generator

### PR DESCRIPTION
**Pull request by serpent213**

### CODE REVIEW

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
Hmm...I approved this, but now I'm not sure. Could you show me an example of what it was generating before and after?

**Comment by serpent213** [comment]
Sure. Before:

```
      <.live_component
        module={ExampleWeb.Live.FormComponent}
```

...which results in

```
** (UndefinedFunctionError) function ExampleWeb.Live.FormComponent.__live__/0 is undefined (module ExampleWeb.Live.FormComponent is not available)
```

After:

```
      <.live_component
        module={ExampleWeb.MemberLive.FormComponent}
```

...which works as expected.

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Comment by dewetblomerus** [comment]
Yea. I can confirm this change was needed. I just ran into it.

**Pull request merged**
